spring.application.name=DISCOVERY-SERVER

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=3000
eureka.server.peer-node-read-timeout-ms=5000

management.endpoints.web.exposure.include=health