spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotel/**
          filters:
            - AuthenticationFilter

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**
          filters:
            - AuthenticationFilter